language: php

matrix:
  include:
    - php: 7.2
      env: ILLUMINATE_VERSION=7.0.*

before_install:
  - composer require "illuminate/cache:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/config:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/console:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

before_script: composer update --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit

after_script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
