language: php

php:
  - 7.0
  - 7.1

before_script: composer install

script:
  - vendor/bin/phpunit

after_script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter
